version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentor-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/mentormate
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: